singleQuote: true
trailingComma: "all"
semi: false
tabWidth: 2
printWidth: 120
bracketSpacing: true
arrowParens: "avoid"
jsxBracketSameLine: true
insertPragma: false
htmlWhitespaceSensitivity: "strict"
endOfLine: "crlf"