query countries {
  countries{
    name
    native
    phone
    continent {
      code
      name
    }
    capital
    languages {
      code
      name
      native
    }
    states {
      code
      name
    }
  }
}